
# Parameters
PARAMETER_WELCOME_BONUS = "WELCOME_BONUS"
PARAMETER_MINIMUM_FEES = "MINIMUM_FEES"
PARAMETER_MINIMUM_WITHDRAW_BTT = "MINIMUM_WITHDRAW_BTT"
PARAMETER_TIP_FEE_BTT = "TIP_FEE_BTT"
PARAMETER_RAIN_FEE_BTT = "RAIN_FEE_BTT"
PARAMETER_AIRDROP_FEE_BTT = "AIRDROP_FEE_BTT"
PARAMETER_MIN_AMOUNT_JOKE = "MIN_AMOUNT_JOKE"

# Parameters Tip Mesaage
PARAMETER_TIP_STANDARD_DRAFT = "TIP_STANDARD_MESSAGE_"
PARAMETER_TIP_SILVER_DRAFT = "TIP_SILVER_MESSAGE_"
PARAMETER_TIP_GOLD_DRAFT = "TIP_GOLD_MESSAGE_"
PARAM_TIP_JOKE_FILENAME_STANDARD = "standard_{joke_nr}"
PARAM_TIP_JOKE_FILENAME_SILVER = "silver_{joke_nr}"
PARAM_TIP_JOKE_FILENAME_GOLD = "gold_{joke_nr}"
PARAMETER_MAX_JOKES = 9

PARAMETER_TIP_EMOJI_STANDARD = "PARAMETER_TIP_EMOJI_STANDARD"
PARAMETER_TIP_EMOJI_SILVER = "PARAMETER_TIP_EMOJI_SILVER"
PARAMETER_TIP_EMOJI_GOLD = "PARAMETER_TIP_EMOJI_GOLD"


PARAMETER_TIP_STANDARD_MESSAGE_1 = "TIP_STANDARD_MESSAGE_1"
PARAMETER_TIP_STANDARD_MESSAGE_2 = "TIP_STANDARD_MESSAGE_2"
PARAMETER_TIP_STANDARD_MESSAGE_3 = "TIP_STANDARD_MESSAGE_3"
PARAMETER_TIP_STANDARD_MESSAGE_4 = "TIP_STANDARD_MESSAGE_4"
PARAMETER_TIP_STANDARD_MESSAGE_5 = "TIP_STANDARD_MESSAGE_5"
PARAMETER_TIP_STANDARD_MESSAGE_6 = "TIP_STANDARD_MESSAGE_6"
PARAMETER_TIP_STANDARD_MESSAGE_7 = "TIP_STANDARD_MESSAGE_7"
PARAMETER_TIP_STANDARD_MESSAGE_8 = "TIP_STANDARD_MESSAGE_8"
PARAMETER_TIP_STANDARD_MESSAGE_9 = "TIP_STANDARD_MESSAGE_9"


PARAMETER_TIP_SILVER_MESSAGE_1 = "TIP_SILVER_MESSAGE_1"
PARAMETER_TIP_SILVER_MESSAGE_2 = "TIP_SILVER_MESSAGE_2"
PARAMETER_TIP_SILVER_MESSAGE_3 = "TIP_SILVER_MESSAGE_3"
PARAMETER_TIP_SILVER_MESSAGE_4 = "TIP_SILVER_MESSAGE_4"
PARAMETER_TIP_SILVER_MESSAGE_5 = "TIP_SILVER_MESSAGE_5"
PARAMETER_TIP_SILVER_MESSAGE_6 = "TIP_SILVER_MESSAGE_6"
PARAMETER_TIP_SILVER_MESSAGE_7 = "TIP_SILVER_MESSAGE_7"
PARAMETER_TIP_SILVER_MESSAGE_8 = "TIP_SILVER_MESSAGE_8"
PARAMETER_TIP_SILVER_MESSAGE_9 = "TIP_SILVER_MESSAGE_9"

PARAMETER_TIP_GOLD_MESSAGE_1 = "TIP_GOLD_MESSAGE_1"
PARAMETER_TIP_GOLD_MESSAGE_2 = "TIP_GOLD_MESSAGE_2"
PARAMETER_TIP_GOLD_MESSAGE_3 = "TIP_GOLD_MESSAGE_3"
PARAMETER_TIP_GOLD_MESSAGE_4 = "TIP_GOLD_MESSAGE_4"
PARAMETER_TIP_GOLD_MESSAGE_5 = "TIP_GOLD_MESSAGE_5"
PARAMETER_TIP_GOLD_MESSAGE_6 = "TIP_GOLD_MESSAGE_6"
PARAMETER_TIP_GOLD_MESSAGE_7 = "TIP_GOLD_MESSAGE_7"
PARAMETER_TIP_GOLD_MESSAGE_8 = "TIP_GOLD_MESSAGE_8"
PARAMETER_TIP_GOLD_MESSAGE_9 = "TIP_GOLD_MESSAGE_9"